project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "LEL2B"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/lecture-01.qmd
        text: Lecture 01
      - href: slides/lecture-02.qmd
        text: Lecture 02

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



