project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "LEL2B"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



